### ISSUE TITLE
api not working

### ISSUE THREAD

**Issue by gokul6350** [VedAstro/VedAstro#16] opened 2023-03-17 09:06 UTC

**Comment by sengiv** [comment] 2023-03-17 09:43
Ahh yes, this is only temporary. Currently in the process of server migration. So API is unstable atm, please try again later. Will close this issue once API server confirmed working.

@gokul6350 thanks for bringing this to our attention

**Comment by sengiv** [comment] 2023-03-18 07:08
![image](https://user-images.githubusercontent.com/43817262/226090659-b771c68b-5c7c-47f3-b4ff-b8d30791e058.png)

## API Server Tested working
Turns out it was just a wrongly set CORS policy.
**Quick tip** : Remember to try out the `beta` version as well, if stable server isn't working
`beta.vedastro.org/api`

**Closed** 2023-03-24 03:26 UTC
Labels: bug
